name: deploy release

run-name: deploy release - ${{ github.sha }}

on:
  push:
    tags:
      'module-v[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy:
    name: deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          Write-Output "I'm a release - yeah!"
        shell: pwsh
        name: release module to PowerShell Gallery
